export const vars = {
    addToSearchUrl: '',
    wordsForSearch: '',
    isLoggedIn: false,
    isAdmin: false,
    currentUserId: '',
    currentUserLogin: '',
    searchResultId: '',
    titleValue: '',
    titleTypeValue: '',
    releaseDateMinValue: '',
    releaseDateMaxValue: '',
    releaseDateValue: '',
    userRatingMinValue: '',
    userRatingMaxValue: '',
    userRatingValue: '',
    numVotesMinValue: '',
    numVotesMaxValue: '',
    numVotesValue: '',
    genresValue: '',
    titleGroupsValue: '',
    titleDataValue: '',
    companiesValue: '',
    certificatesValue: '',
    colorInfoValue: '',
    countriesValue: '',
    keywordsValue: '',
    languagesValue: '',
    filmingLocationsValue: '',
    popularityMinValue: '',
    popularityMaxValue: '',
    popularityValue: '',
    plotValue: '',
    runtimeValue: '',
    runtimeMinValue: '',
    runtimeMaxValue: '',
    soundMixValue: '',
    numberPerPageValue: '',
    sortByValue: '',
}

export const prefix = 'https://it-academy-js-api-zmicerboksha.vercel.app/api/4/pg/'
export const queryDatabase = (...args) => fetch(...args).then((res) => res.json())
export const body = document.querySelector('body')
export const menuBar = document.querySelector('nav#menuBar')
export const userMenuButton = document.querySelector('#userMenuButton')
export const userMenuList = document.querySelector('#userMenuList')
export const yourWatchlistButton = document.querySelector('#yourWatchlistButton')
export const editProfileButton = document.querySelector('#editProfileButton')
export const userListButton = document.querySelector('#userListButton')
export const logOutButton = document.querySelector('#logOutAcc')
export const main = document.querySelector('#main')
export const comingSoon = document.querySelector('#comingSoon')
export const inTheaters = document.querySelector('#inTheaters')
export const boxOffice = document.querySelector('#boxOffice')
export const mostPopularMovies = document.querySelector('#mostPopularMovies')
export const mostPopularTVs = document.querySelector('#mostPopularTVs')
export const top250Movies = document.querySelector('#top250Movies')
export const top250TVs = document.querySelector('#top250TVs')
export const searchField = document.querySelector('#searchField')
export const searchButton = document.querySelector('#searchButton')
export const listOfSearchResults = document.querySelector('#listOfSearchResults')
export const advancedSearch = document.querySelector('#advancedSearch')
export const loginButton = document.querySelector('#loginButton')
export const signInEmail = document.querySelector('#signin-email')
export const signInPassword = document.querySelector('#signin-password')
export const openPasswordButton = document.querySelector('#openPassword')
export const signUpValidationLogin = document.querySelector('.signUpValidationLogin')
export const signUpValidationEmail = document.querySelector('.signUpValidationEmail')
export const signUpValidationPassword = document.querySelector('.signUpValidationPassword')
export const signInLogin = document.querySelector('#signin-login')
export const logInPassword = document.querySelector('#login-password')
export const logInLogin = document.querySelector('#login-login')
export const login = document.querySelector('#login')
export const signUp = document.querySelector('#signUp')
export const loginValidationLogin = document.querySelector('.loginValidationLogin')
export const loginValidationPassword = document.querySelector('.loginValidationPassword')
export const searchResult = document.querySelector('#searchResult')
export const personalWatchlist = document.querySelector('#personalWatchlist')
export const editProfile = document.querySelector('#editProfile')
export const userList = document.querySelector('#userList')
export const deleteWindow = document.querySelector('.deleteWindow')
export const deleteAccButton = document.querySelector('#deleteAcc')
export const showDeleteWindow = document.querySelector('#showDeleteAcc')
export const closeDeleteWindow = document.querySelector('#hideDeleteAcc')
export const tbody = document.querySelector('#userListTableBody')
export const titleForReview = document.querySelector('.reviewTitleContainer>input')
export const textareaForReview = document.querySelector('.reviewPlotContainer>textarea')
export const containSpoilersRadio = document.querySelectorAll('.spoilers')
export const validationTitle = document.querySelector('.reviewValidation.title')
export const validationPlot = document.querySelector('.reviewValidation.plot')
export const validationSpoilers = document.querySelector('.reviewValidation.spoilers')
export const buttonToSubmitReview = document.querySelector('#submitReview')
export const editAccButton = document.querySelector('#editAcc')
export const newLoginField = document.querySelector('#newLoginField')
export const newEmailField = document.querySelector('#newEmailField')
export const oldPasswordField = document.querySelector('#oldPasswordField')
export const newPasswordField = document.querySelector('#newPasswordField')
export const showOldPassword = document.querySelector('#showOldPassword')
export const showNewPassword = document.querySelector('#showNewPassword')
export const validationOldPass = document.querySelector('.validationOldPass')
export const validationNewPass = document.querySelector('.validationNewPass')

export const advancedSearchUrl = 'https://imdb-api.com/en/API/AdvancedSearch/k_ibyc30ko'
export const title = document.querySelector('.formControl.title')
export const titleType = document.querySelector('.inputs.titleType')
export const releaseDateMin = document.querySelector('.releaseDateMin')
export const releaseDateMax = document.querySelector('.releaseDateMax')
export const userRatingMin = document.querySelector('.userRatingMin')
export const userRatingMax = document.querySelector('.userRatingMax')
export const numVotesMin = document.querySelector('.numVotesMin')
export const numVotesMax = document.querySelector('.numVotesMax')
export const genres = document.querySelector('.genres')
export const titleGroups = document.querySelector('.titleGroups')
export const titleData = document.querySelector('.titleData')
export const companies = document.querySelector('.companies')
export const certificates = document.querySelector('.certificates')
export const colorInfo = document.querySelector('.colorInfo')
export const countries = document.querySelector('.countries')
export const keywords = document.querySelector('#keywords')
export const languages = document.querySelector('.languages')
export const filmingLocations = document.querySelector('.filmingLocations')
export const popularityMin = document.querySelector('.moviemeterMin')
export const popularityMax = document.querySelector('.moviemeterMax')
export const plot = document.querySelector('.plot')
export const runtimeMin = document.querySelector('.runtimeMin')
export const runtimeMax = document.querySelector('.runtimeMax')
export const soundMix = document.querySelector('.soundMix')
export const numberPerPage = document.querySelector('#numberPerPage')
export const sortBy = document.querySelector('.sortBy')
export const advancedSearchButton = document.querySelector('#advancedSearchButton')
export const titleTypeArray = [
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-1',
        value: 'feature',
        labelName: 'Feature Film',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-2',
        value: 'tv_movie',
        labelName: 'TV Movie',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-3',
        value: 'tv_series',
        labelName: 'TV Series',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-4',
        value: 'tv_episode',
        labelName: 'TV Episode',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-5',
        value: 'tv_special',
        labelName: 'TV Special',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-6',
        value: 'tv_miniseries',
        labelName: 'Mini-Series',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-7',
        value: 'documentary',
        labelName: 'Documentary',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-8',
        value: 'short',
        labelName: 'Short Film',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-9',
        value: 'video',
        labelName: 'Video',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-10',
        value: 'tv_short',
        labelName: 'TV Short',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-11',
        value: 'podcast_series',
        labelName: 'Podcast Series',
    },
    {
        class: 'AdvSearchInput',
        name: 'title_type',
        id: 'title_type-12',
        value: 'podcast_episode',
        labelName: 'Podcast Episode',
    },
]
export const userRatingArray = [
    {
        value: '',
        selected: '',
        content: '-'
    },
    { content: 1.0 },
    { content: 1.1 },
    { content: 1.2 },
    { content: 1.3 },
    { content: 1.4 },
    { content: 1.5 },
    { content: 1.6 },
    { content: 1.7 },
    { content: 1.8 },
    { content: 1.9 },
    { content: 2.0 },
    { content: 2.1 },
    { content: 2.2 },
    { content: 2.3 },
    { content: 2.4 },
    { content: 2.5 },
    { content: 2.6 },
    { content: 2.7 },
    { content: 2.8 },
    { content: 2.9 },
    { content: 3.0 },
    { content: 3.1 },
    { content: 3.2 },
    { content: 3.3 },
    { content: 3.4 },
    { content: 3.5 },
    { content: 3.6 },
    { content: 3.7 },
    { content: 3.8 },
    { content: 3.9 },
    { content: 4.0 },
    { content: 4.1 },
    { content: 4.2 },
    { content: 4.3 },
    { content: 4.4 },
    { content: 4.5 },
    { content: 4.6 },
    { content: 4.7 },
    { content: 4.8 },
    { content: 4.9 },
    { content: 5.0 },
    { content: 5.1 },
    { content: 5.2 },
    { content: 5.3 },
    { content: 5.4 },
    { content: 5.5 },
    { content: 5.6 },
    { content: 5.7 },
    { content: 5.8 },
    { content: 5.9 },
    { content: 6.0 },
    { content: 6.1 },
    { content: 6.2 },
    { content: 6.3 },
    { content: 6.4 },
    { content: 6.5 },
    { content: 6.6 },
    { content: 6.7 },
    { content: 6.8 },
    { content: 6.9 },
    { content: 7.0 },
    { content: 7.1 },
    { content: 7.2 },
    { content: 7.3 },
    { content: 7.4 },
    { content: 7.5 },
    { content: 7.6 },
    { content: 7.7 },
    { content: 7.8 },
    { content: 7.9 },
    { content: 8.0 },
    { content: 8.1 },
    { content: 8.2 },
    { content: 8.3 },
    { content: 8.4 },
    { content: 8.5 },
    { content: 8.6 },
    { content: 8.7 },
    { content: 8.8 },
    { content: 8.9 },
    { content: 9.0 },
    { content: 9.1 },
    { content: 9.2 },
    { content: 9.3 },
    { content: 9.4 },
    { content: 9.5 },
    { content: 9.6 },
    { content: 9.7 },
    { content: 9.8 },
    { content: 9.9 },
    { content: 10 },
]
export const genresArray = [
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-1',
        value: 'action',
        labelName: 'Action',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-2',
        value: 'adventure',
        labelName: 'Adventure',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-3',
        value: 'animation',
        labelName: 'Animation',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-4',
        value: 'biography',
        labelName: 'Biography',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-5',
        value: 'comedy',
        labelName: 'Comedy',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-6',
        value: 'crime',
        labelName: 'Crime',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-7',
        value: 'documentary',
        labelName: 'Documentary',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-8',
        value: 'drama',
        labelName: 'Drama',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-9',
        value: 'family',
        labelName: 'Family',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-10',
        value: 'fantasy',
        labelName: 'Fantasy',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-11',
        value: 'film_noir',
        labelName: 'Film-Noir',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-12',
        value: 'game_show',
        labelName: 'Game-Show',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-13',
        value: 'history',
        labelName: 'History',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-14',
        value: 'horror',
        labelName: 'Horror',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-15',
        value: 'music',
        labelName: 'Music',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-16',
        value: 'musical',
        labelName: 'Musical',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-17',
        value: 'mystery',
        labelName: 'Mystery',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-18',
        value: 'news',
        labelName: 'News',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-19',
        value: 'reality_tv',
        labelName: 'Reality-TV',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-20',
        value: 'romance',
        labelName: 'Romance',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-21',
        value: 'sci_fi',
        labelName: 'Sci-Fi',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-22',
        value: 'sport',
        labelName: 'Sport',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-23',
        value: 'talk_show',
        labelName: 'Talk-Show',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-24',
        value: 'thriller',
        labelName: 'Thriller',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-25',
        value: 'war',
        labelName: 'War',
    },
    {
        class: 'AdvSearchInput',
        name: 'genres',
        id: 'genres-26',
        value: 'western',
        labelName: 'Western',
    },
]
export const titleGroupsArray = [
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-1',
        value: 'top_100',
        labelName: 'IMDb "Top 100"',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-2',
        value: 'top_250',
        labelName: 'IMDb "Top 250"',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-3',
        value: 'top_1000',
        labelName: 'IMDb "Top 1000"',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-4',
        value: 'oscar_winners',
        labelName: 'Oscar-Winning',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-5',
        value: 'emmy_winners',
        labelName: 'Emmy Award-Winning',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-6',
        value: 'golden_globe_winners',
        labelName: 'Golden Globe-Winning',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-7',
        value: 'oscar_nominees',
        labelName: 'Oscar-Nominated',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-8',
        value: 'emmy_nominees',
        labelName: 'Emmy Award-Nominated',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-9',
        value: 'golden_globe_nominees',
        labelName: 'Golden Globe-Nominated',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-10',
        value: 'oscar_best_picture_winners',
        labelName: 'Best Picture-Winning',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-11',
        value: 'oscar_best_director_winners',
        labelName: 'Best Director-Winning',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-12',
        value: 'now-playing-us',
        labelName: 'Now-Playing',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-13',
        value: 'oscar_best_picture_nominees',
        labelName: 'Best Picture-Nominated',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-14',
        value: 'oscar_best_director_nominees',
        labelName: 'Best Director-Nominated',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-15',
        value: 'national_film_registry',
        labelName: 'National Film Board Preserved',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-16',
        value: 'razzie_winners',
        labelName: 'Razzie-Winning',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-17',
        value: 'bottom_100',
        labelName: 'IMDb "Bottom 100"',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-18',
        value: 'bottom_250',
        labelName: 'IMDb "Bottom 250"',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-19',
        value: 'razzie_nominees',
        labelName: 'Razzie-Nominated',
    },
    {
        class: 'AdvSearchInput',
        name: 'groups',
        id: 'titleGroups-20',
        value: 'bottom_1000',
        labelName: 'IMDb "Bottom 1000"',
    },
]
export const titleDataArray = [
    { value: "alternate-versions", content: 'Alternate Versions' },
    { value: "awards", content: 'Awards' },
    { value: "business-info", content: 'Business Info' },
    { value: "crazy-credits", content: 'Crazy Credits' },
    { value: "goofs", content: 'Goofs' },
    { value: "locations", content: 'Locations' },
    { value: "plot", content: 'Plot' },
    { value: "quotes", content: 'Quotes' },
    { value: "soundtracks", content: 'Soundtracks' },
    { value: "technical", content: 'Technical Info' },
    { value: "trivia", content: 'Trivia' },
    { value: "x-ray", content: 'X - Ray' },
]
export const companiesArray = [
    {
        class: 'AdvSearchInput',
        name: 'companies',
        id: 'companies-1',
        value: 'fox',
        labelName: '20th Century Fox',
    },
    {
        class: 'AdvSearchInput',
        name: 'companies',
        id: 'companies-2',
        value: 'columbia',
        labelName: 'Sony',
    },
    {
        class: 'AdvSearchInput',
        name: 'companies',
        id: 'companies-3',
        value: 'dreamworks',
        labelName: 'DreamWorks',
    },
    {
        class: 'AdvSearchInput',
        name: 'companies',
        id: 'companies-4',
        value: 'mgm',
        labelName: 'MGM',
    },
    {
        class: 'AdvSearchInput',
        name: 'companies',
        id: 'companies-5',
        value: 'paramount',
        labelName: 'Paramount',
    },
    {
        class: 'AdvSearchInput',
        name: 'companies',
        id: 'companies-6',
        value: 'universal',
        labelName: 'Universal',
    },
    {
        class: 'AdvSearchInput',
        name: 'companies',
        id: 'companies-7',
        value: 'disney',
        labelName: 'Walt Disney',
    },
    {
        class: 'AdvSearchInput',
        name: 'companies',
        id: 'companies-8',
        value: 'warner',
        labelName: 'Warner Bros.',
    },
]
export const certificatesArray = [
    {
        class: 'AdvSearchInput',
        name: 'certificates',
        id: 'certificates-1',
        value: 'us:G',
        labelName: 'G',
    },
    {
        class: 'AdvSearchInput',
        name: 'certificates',
        id: 'certificates-2',
        value: 'us:PG',
        labelName: 'PG',
    },
    {
        class: 'AdvSearchInput',
        name: 'certificates',
        id: 'certificates-3',
        value: 'us:PG-13',
        labelName: 'PG-13',
    },
    {
        class: 'AdvSearchInput',
        name: 'certificates',
        id: 'certificates-4',
        value: 'us:R',
        labelName: 'R',
    },
    {
        class: 'AdvSearchInput',
        name: 'certificates',
        id: 'certificates-5',
        value: 'us:NC-17',
        labelName: 'NC-17',
    },
]
export const colorInfoArray = [
    {
        class: 'AdvSearchInput',
        name: 'colors',
        id: 'colors-1',
        value: 'color',
        labelName: 'Color',
    },
    {
        class: 'AdvSearchInput',
        name: 'colors',
        id: 'colors-2',
        value: 'black_and_white',
        labelName: 'Black & White',
    },
    {
        class: 'AdvSearchInput',
        name: 'colors',
        id: 'colors-3',
        value: 'colorized',
        labelName: 'Colorized',
    },
    {
        class: 'AdvSearchInput',
        name: 'colors',
        id: 'colors-4',
        value: 'aces',
        labelName: 'ACES',
    },
]
export const soundMixArray = [
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-1',
        value: 'mono',
        labelName: 'Mono',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-2',
        value: 'silent',
        labelName: 'Silent',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-3',
        value: 'stereo',
        labelName: 'Stereo',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-4',
        value: 'dolby_digital',
        labelName: 'Dolby Digital',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-5',
        value: 'dolby',
        labelName: 'Dolby',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-6',
        value: 'dolby_sr',
        labelName: 'Dolby SR',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-6',
        value: 'dolby_sr',
        labelName: 'Dolby SR',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-7',
        value: 'dts',
        labelName: 'DTS',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-8',
        value: 'sdds',
        labelName: 'SDDS',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-9',
        value: 'ultra_stereo',
        labelName: 'Ultra Stereo',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-10',
        value: '4_track_stereo',
        labelName: '4-Track Stereo',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-11',
        value: '70_mm_6_track',
        labelName: '70 mm 6-Track',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-12',
        value: 'vitaphone',
        labelName: 'Vitaphone',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-13',
        value: 'dolby_digital_ex',
        labelName: 'Dolby Digital EX',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-14',
        value: 'de_forest_phonofilm',
        labelName: 'De Forest Phonofilm',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-15',
        value: 'dts_stereo',
        labelName: 'DTS-Stereo',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-16',
        value: 'chronophone',
        labelName: 'Chronophone',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-17',
        value: '6_track_stereo',
        labelName: '6-Track Stereo',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-18',
        value: 'dts_es',
        labelName: 'DTS-ES',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-19',
        value: 'perspecta_stereo',
        labelName: 'Perspecta Stereo',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-20',
        value: 'cinephone',
        labelName: 'Cinephone',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-21',
        value: '3_channel_stereo',
        labelName: '3 Channel Stereo',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-22',
        value: 'cinematophone',
        labelName: 'Cinematophone',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-23',
        value: 'sonics_ddp',
        labelName: 'Sonics-DDP',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-24',
        value: '12_track_digital_sound',
        labelName: '12-Track Digital Sound',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-25',
        value: 'dts_70_mm',
        labelName: 'DTS 70 mm',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-26',
        value: 'imax_6_track',
        labelName: 'IMAX 6-Track',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-27',
        value: 'matrix_surround',
        labelName: 'Matrix Surround',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-28',
        value: 'sonix',
        labelName: 'Sonix',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-29',
        value: 'sensurround',
        labelName: 'Sensurround',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-30',
        value: 'cinerama_7_track',
        labelName: 'Cinerama 7-Track',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-31',
        value: 'kinoplasticon',
        labelName: 'Kinoplasticon',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-32',
        value: 'digitrac_digital_audio_system',
        labelName: 'Digitrac Digital Audio System',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-33',
        value: 'cinesound',
        labelName: 'Cinesound',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-34',
        value: 'phono_kinema',
        labelName: 'Phono-Kinema',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-35',
        value: 'cds',
        labelName: 'CDS',
    },
    {
        class: 'AdvSearchInput',
        name: 'soundMixes',
        id: 'soundMixes-36',
        value: 'lc_concept_digital_sound',
        labelName: 'LC-Concept Digital Sound',
    },
]
export const sortByArray = [
    {
        selected: "",
        value: "moviemeter,asc", content: 'Popularity Ascending'
    },
    {
        value: "moviemeter,desc", content: 'Popularity Descending'
    },
    {
        value: "alpha,asc", content: 'A - Z Ascending'
    },
    {
        value: "alpha,desc", content: 'A - Z Descending'
    },
    {
        value: "user_rating,asc", content: 'User Rating Ascending'
    },
    {
        value: "user_rating,desc", content: 'User Rating Descending'
    },
    {
        value: "num_votes,asc", content: 'Num Votes Ascending'
    },
    {
        value: "num_votes,desc", content: 'Num Votes Descending'
    },
    {
        value: "boxoffice_gross_us,asc", content: 'US Box Office Ascending'
    },
    {
        value: "boxoffice_gross_us,desc", content: 'US Box Office Descending'
    },
    {
        value: "runtime,asc", content: 'Runtime Ascending'
    },
    {
        value: "runtime,desc", content: 'Runtime Descending'
    },
    {
        value: "year,asc", content: 'Year Ascending'
    },
    {
        value: "year,desc", content: 'Year Descending'
    },
    {
        value: "release_date,asc", content: 'Release Date Ascending '
    },
    {
        value: "release_date,desc", content: 'Release Date Descending '
    },
]
export const countriesArray = [
    { value: "af", content: 'Afghanistan' },
    { value: "ax", content: 'Åland Islands' },
    { value: "al", content: 'Albania ' },
    { value: "dz", content: 'Algeria' },
    { value: "as", content: 'American Samoa' },
    { value: "ad", content: 'Andorra' },
    { value: "ao", content: 'Angola' },
    { value: "ai", content: 'Anguilla' },
    { value: "aq", content: 'Antarctica' },
    { value: "ag", content: 'Antigua and Barbuda' },
    { value: "ar", content: 'Argentina' },
    { value: "am", content: 'Armenia' },
    { value: "aw", content: 'Aruba' },
    { value: "au", content: 'Australia' },
    { value: "at", content: 'Austria' },
    { value: "az", content: 'Azerbaijan' },
    { value: "bs", content: 'Bahamas' },
    { value: "bh", content: 'Bahrain' },
    { value: "bd", content: 'Bangladesh' },
    { value: "bb", content: 'Barbados' },
    { value: "by", content: 'Belarus' },
    { value: "be", content: 'Belgium' },
    { value: "bz", content: 'Belize' },
    { value: "bj", content: 'Benin' },
    { value: "bm", content: 'Bermuda' },
    { value: "bt", content: 'Bhutan' },
    { value: "bo", content: 'Bolivia' },
    { value: "bq", content: 'Bonaire, Sint Eustatius and Saba' },
    { value: "ba", content: 'Bosnia and Herzegovina' },
    { value: "bw", content: 'Botswana' },
    { value: "bv", content: 'Bouvet Island' },
    { value: "br", content: 'Brazil' },
    { value: "io", content: 'British Indian Ocean Territory' },
    { value: "vg", content: 'British Virgin Islands' },
    { value: "bn", content: 'Brunei Darussalam' },
    { value: "bg", content: 'Bulgaria' },
    { value: "bf", content: 'Burkina Faso' },
    { value: "bumm", content: 'Burma' },
    { value: "bi", content: 'Burundi' },
    { value: "kh", content: 'Cambodia' },
    { value: "cm", content: 'Cameroon' },
    { value: "ca", content: 'Canada' },
    { value: "cv", content: 'Cape Verde' },
    { value: "ky", content: 'Cayman Islands' },
    { value: "cf", content: 'Central African Republic' },
    { value: "td", content: 'Chad' },
    { value: "cl", content: 'Chile' },
    { value: "cn", content: 'China' },
    { value: "cx", content: 'Christmas Island' },
    { value: "cc", content: 'Cocos(Keeling) Islands' },
    { value: "co", content: 'Colombia' },
    { value: "km", content: 'Comoros' },
    { value: "cg", content: 'Congo' },
    { value: "ck", content: 'Cook Islands' },
    { value: "cr", content: 'Costa Rica' },
    { value: "ci", content: `Côte d'Ivoire` },
    { value: "hr", content: 'Croatia' },
    { value: "cu", content: 'Cuba' },
    { value: "cy", content: 'Cyprus' },
    { value: "cz", content: 'Czech Republic' },
    { value: "cshh", content: 'Czechoslovakia' },
    { value: "cd", content: 'Democratic Republic of the Congo' },
    { value: "dk", content: 'Denmark' },
    { value: "dj", content: 'Djibouti' },
    { value: "dm", content: 'Dominica' },
    { value: "do", content: 'Dominican Republic' },
    { value: "ddde", content: 'East Germany' },
    { value: "ec", content: 'Ecuador' },
    { value: "eg", content: 'Egypt' },
    { value: "sv", content: 'El Salvador' },
    { value: "gq", content: 'Equatorial Guinea' },
    { value: "er", content: 'Eritrea' },
    { value: "ee", content: 'Estonia' },
    { value: "et", content: 'Ethiopia' },
    { value: "fk", content: 'Falkland Islands' },
    { value: "fo", content: 'Faroe Islands' },
    { value: "yucs", content: 'Federal Republic of Yugoslavia' },
    { value: "fm", content: 'Federated States of Micronesia' },
    { value: "fj", content: 'Fiji' },
    { value: "fi", content: 'Finland' },
    { value: "fr", content: 'France' },
    { value: "gf", content: 'French Guiana' },
    { value: "pf", content: 'French Polynesia' },
    { value: "tf", content: 'French Southern Territories' },
    { value: "ga", content: 'Gabon' },
    { value: "gm", content: 'Gambia' },
    { value: "ge", content: 'Georgia' },
    { value: "de", content: 'Germany' },
    { value: "gh", content: 'Ghana' },
    { value: "gi", content: 'Gibraltar' },
    { value: "gr", content: 'Greece' },
    { value: "gl", content: 'Greenland' },
    { value: "gd", content: 'Grenada' },
    { value: "gp", content: 'Guadeloupe' },
    { value: "gu", content: 'Guam' },
    { value: "gt", content: 'Guatemala' },
    { value: "gg", content: 'Guernsey' },
    { value: "gn", content: 'Guinea' },
    { value: "gw", content: 'Guinea - Bissau' },
    { value: "gy", content: 'Guyana' },
    { value: "ht", content: 'Haiti' },
    { value: "hm", content: 'Heard Island and McDonald Islands' },
    { value: "va", content: 'Holy See(Vatican City State)' },
    { value: "hn", content: 'Honduras' },
    { value: "hk", content: 'Hong Kong' },
    { value: "hu", content: 'Hungary' },
    { value: "is", content: 'Iceland' },
    { value: "in", content: 'India' },
    { value: "id", content: 'Indonesia' },
    { value: "ir", content: 'Iran' },
    { value: "iq", content: 'Iraq' },
    { value: "ie", content: 'Ireland' },
    { value: "im", content: 'Isle of Man' },
    { value: "il", content: 'Israel' },
    { value: "it", content: 'Italy' },
    { value: "jm", content: 'Jamaica' },
    { value: "jp", content: 'Japan' },
    { value: "je", content: 'Jersey' },
    { value: "jo", content: 'Jordan' },
    { value: "kz", content: 'Kazakhstan' },
    { value: "ke", content: 'Kenya' },
    { value: "ki", content: 'Kiribati' },
    { value: "xko", content: 'Korea' },
    { value: "xkv", content: 'Kosovo' },
    { value: "kw", content: 'Kuwait' },
    { value: "kg", content: 'Kyrgyzstan' },
    { value: "la", content: 'Laos' },
    { value: "lv", content: 'Latvia' },
    { value: "lb", content: 'Lebanon' },
    { value: "ls", content: 'Lesotho' },
    { value: "lr", content: 'Liberia' },
    { value: "ly", content: 'Libya' },
    { value: "li", content: 'Liechtenstein' },
    { value: "lt", content: 'Lithuania' },
    { value: "lu", content: 'Luxembourg' },
    { value: "mo", content: 'Macao' },
    { value: "mg", content: 'Madagascar' },
    { value: "mw", content: 'Malawi' },
    { value: "my", content: 'Malaysia' },
    { value: "mv", content: 'Maldives' },
    { value: "ml", content: 'Mali' },
    { value: "mt", content: 'Malta' },
    { value: "mh", content: 'Marshall Islands' },
    { value: "mq", content: 'Martinique' },
    { value: "mr", content: 'Mauritania' },
    { value: "mu", content: 'Mauritius' },
    { value: "yt", content: 'Mayotte' },
    { value: "mx", content: 'Mexico' },
    { value: "md", content: 'Moldova' },
    { value: "mc", content: 'Monaco' },
    { value: "mn", content: 'Mongolia' },
    { value: "me", content: 'Montenegro' },
    { value: "ms", content: 'Montserrat' },
    { value: "ma", content: 'Morocco' },
    { value: "mz", content: 'Mozambique' },
    { value: "mm", content: 'Myanmar' },
    { value: "na", content: 'Namibia' },
    { value: "nr", content: 'Nauru' },
    { value: "np", content: 'Nepal' },
    { value: "nl", content: 'Netherlands' },
    { value: "an", content: 'Netherlands Antilles' },
    { value: "nc", content: 'New Caledonia' },
    { value: "nz", content: 'New Zealand' },
    { value: "ni", content: 'Nicaragua' },
    { value: "ne", content: 'Niger' },
    { value: "ng", content: 'Nigeria' },
    { value: "nu", content: 'Niue' },
    { value: "nf", content: 'Norfolk Island' },
    { value: "kp", content: 'North Korea' },
    { value: "vdvn", content: 'North Vietnam' },
    { value: "mp", content: 'Northern Mariana Islands' },
    { value: "no", content: 'Norway' },
    { value: "om", content: 'Oman' },
    { value: "pk", content: 'Pakistan' },
    { value: "pw", content: 'Palau' },
    { value: "xpi", content: 'Palestine' },
    { value: "ps", content: 'Palestinian Territory' },
    { value: "pa", content: 'Panama' },
    { value: "pg", content: 'Papua New Guinea' },
    { value: "py", content: 'Paraguay' },
    { value: "pe", content: 'Peru' },
    { value: "ph", content: 'Philippines' },
    { value: "pl", content: 'Poland' },
    { value: "pt", content: 'Portugal' },
    { value: "pn", content: 'Pitcairn' },
    { value: "pr", content: 'Puerto Rico ' },
    { value: "qa", content: 'Qatar' },
    { value: "mk", content: 'Republic of Macedonia' },
    { value: "re", content: 'Réunion' },
    { value: "ro", content: 'Romania' },
    { value: "ru", content: 'Russia' },
    { value: "rw", content: 'Rwanda' },
    { value: "bl", content: 'Saint Barthélemy' },
    { value: "sh", content: 'Saint Helena' },
    { value: "kn", content: 'Saint Kitts and Nevis' },
    { value: "lc", content: 'Saint Lucia' },
    { value: "mf", content: 'Saint Martin(French part)' },
    { value: "pm", content: 'Saint Pierre and Miquelon' },
    { value: "vc", content: 'Saint Vincent and the Grenadines' },
    { value: "ws", content: 'Samoa' },
    { value: "sm", content: 'San Marino' },
    { value: "st", content: 'Sao Tome and Principe' },
    { value: "sa", content: 'Saudi Arabia' },
    { value: "sn", content: 'Senegal' },
    { value: "rs", content: 'Serbia' },
    { value: "csxx", content: 'Serbia and Montenegro' },
    { value: "sc", content: 'Seychelles' },
    { value: "xsi", content: 'Siam' },
    { value: "sl", content: 'Sierra Leone' },
    { value: "sg", content: 'Singapore' },
    { value: "sk", content: 'Slovakia' },
    { value: "si", content: 'Slovenia' },
    { value: "sb", content: 'Solomon Islands' },
    { value: "so", content: 'Somalia' },
    { value: "za", content: 'South Africa' },
    { value: "gs", content: 'South Georgia and the South Sandwich Islands' },
    { value: "kr", content: 'South Korea' },
    { value: "suhh", content: 'Soviet Union' },
    { value: "es", content: 'Spain' },
    { value: "lk", content: 'Sri Lanka' },
    { value: "sd", content: 'Sudan' },
    { value: "sr", content: 'Suriname' },
    { value: "sj", content: 'Svalbard and Jan Mayen' },
    { value: "sz", content: 'Swaziland' },
    { value: "se", content: 'Sweden' },
    { value: "ch", content: 'Switzerland' },
    { value: "sy", content: 'Syria' },
    { value: "tw", content: 'Taiwan' },
    { value: "tj", content: 'Tajikistan' },
    { value: "tz", content: 'Tanzania' },
    { value: "th", content: 'Thailand' },
    { value: "tl", content: 'Timor - Leste' },
    { value: "tg", content: 'Togo' },
    { value: "tk", content: 'Tokelau' },
    { value: "to", content: 'Tonga' },
    { value: "tt", content: 'Trinidad and Tobago' },
    { value: "tn", content: 'Tunisia' },
    { value: "tr", content: 'Turkey' },
    { value: "tm", content: 'Turkmenistan' },
    { value: "tc", content: 'Turks and Caicos Islands' },
    { value: "tv", content: 'Tuvalu' },
    { value: "vi", content: 'U.S.Virgin Islands' },
    { value: "ug", content: 'Uganda' },
    { value: "ua", content: 'Ukraine' },
    { value: "ae", content: 'United Arab Emirates' },
    { value: "gb", content: 'United Kingdom' },
    { value: "us", content: 'United States' },
    { value: "um", content: 'United States Minor Outlying Islands' },
    { value: "uy", content: 'Uruguay' },
    { value: "uz", content: 'Uzbekistan' },
    { value: "vu", content: 'Vanuatu' },
    { value: "ve", content: 'Venezuela' },
    { value: "vn", content: 'Vietnam' },
    { value: "wf", content: 'Wallis and Futuna' },
    { value: "xwg", content: 'West Germany' },
    { value: "eh", content: 'Western Sahara' },
    { value: "ye", content: 'Yemen' },
    { value: "xyu", content: 'Yugoslavia' },
    { value: "zrcd", content: 'Zaire' },
    { value: "zm", content: 'Zambia' },
    { value: "zw", content: 'Zimbabwe' },
]
export const languagesArray = [
    { value: "ab", content: 'Abkhazian' },
    { value: "qac", content: 'Aboriginal' },
    { value: "guq", content: 'Aché' },
    { value: "qam", content: 'Acholi' },
    { value: "af", content: 'Afrikaans' },
    { value: "qas", content: 'Aidoukrou' },
    { value: "ak", content: 'Akan' },
    { value: "sq", content: 'Albanian' },
    { value: "ale", content: 'Aleut' },
    { value: "alg", content: 'Algonquin' },
    { value: "ase", content: 'American Sign Language' },
    { value: "am", content: 'Amharic' },
    { value: "apa", content: 'Apache languages' },
    { value: "ar", content: 'Arabic' },
    { value: "an", content: 'Aragonese' },
    { value: "arc", content: 'Aramaic' },
    { value: "arp", content: 'Arapaho' },
    { value: "aqc", content: 'Archi' },
    { value: "hy", content: 'Armenian' },
    { value: "as", content: 'Assamese' },
    { value: "asb", content: 'Assiniboine' },
    { value: "aii", content: 'Assyrian Neo- Aramaic' },
    { value: "ath", content: 'Athapascan languages' },
    { value: "asf", content: 'Australian Sign Language' },
    { value: "awa", content: 'Awadhi' },
    { value: "ay", content: 'Aymara' },
    { value: "az", content: 'Azerbaijani' },
    { value: "ast", content: 'Bable' },
    { value: "qbd", content: 'Baka' },
    { value: "ban", content: 'Balinese' },
    { value: "bm", content: 'Bambara' },
    { value: "ba", content: 'Bashkir' },
    { value: "eu", content: 'Basque' },
    { value: "bsc", content: 'Bassari' },
    { value: "be", content: 'Belarusian' },
    { value: "bem", content: 'Bemba' },
    { value: "bn", content: 'Bengali' },
    { value: "ber", content: 'Berber languages' },
    { value: "bho", content: 'Bhojpuri' },
    { value: "qbi", content: 'Bicolano' },
    { value: "qbh", content: 'Bodo' },
    { value: "bfw", content: 'Bonda' },
    { value: "bs", content: 'Bosnian' },
    { value: "bzs", content: 'Brazilian Sign Language' },
    { value: "br", content: 'Breton' },
    { value: "bfi", content: 'British Sign Language' },
    { value: "bg", content: 'Bulgarian' },
    { value: "my", content: 'Burmese' },
    { value: "bsk", content: 'Burushaski' },
    { value: "yue", content: 'Cantonese' },
    { value: "ca", content: 'Catalan' },
    { value: "km", content: 'Central Khmer' },
    { value: "ccp", content: 'Chakma' },
    { value: "qax", content: 'Chaozhou' },
    { value: "ce", content: 'Chechen' },
    { value: "chr", content: 'Cherokee' },
    { value: "chy", content: 'Cheyenne' },
    { value: "hne", content: 'Chhattisgarhi' },
    { value: "zh", content: 'Chinese' },
    { value: "ckt", content: 'Chukchi' },
    { value: "kw", content: 'Cornish' },
    { value: "co", content: 'Corsican' },
    { value: "cr", content: 'Cree' },
    { value: "mus", content: 'Creek' },
    { value: "hr", content: 'Croatian' },
    { value: "cro", content: 'Crow' },
    { value: "cs", content: 'Czech' },
    { value: "da", content: 'Danish' },
    { value: "prs", content: 'Dari' },
    { value: "dso", content: 'Desiya' },
    { value: "din", content: 'Dinka' },
    { value: "qaw", content: 'Djerma' },
    { value: "doi", content: 'Dogri' },
    { value: "nl", content: 'Dutch' },
    { value: "dyu", content: 'Dyula' },
    { value: "dz", content: 'Dzongkha' },
    { value: "qbc", content: 'East - Greenlandic' },
    { value: "frs", content: 'Eastern Frisian' },
    { value: "egy", content: 'Egyptian(Ancient)' },
    { value: "en", content: 'English' },
    { value: "eo", content: 'Esperanto' },
    { value: "et", content: 'Estonian' },
    { value: "ee", content: 'Ewe' },
    { value: "qbg", content: 'Faliasch' },
    { value: "fo", content: 'Faroese' },
    { value: "fil", content: 'Filipino' },
    { value: "fi", content: 'Finnish' },
    { value: "qbn", content: 'Flemish' },
    { value: "fon", content: 'Fon' },
    { value: "fr", content: 'French' },
    { value: "fsl", content: 'French Sign Language' },
    { value: "fur", content: 'Friulian' },
    { value: "ff", content: 'Fulah' },
    { value: "fvr", content: 'Fur' },
    { value: "gd", content: 'Gaelic' },
    { value: "gl", content: 'Galician' },
    { value: "ka", content: 'Georgian' },
    { value: "de", content: 'German' },
    { value: "gsg", content: 'German Sign Language' },
    { value: "grb", content: 'Grebo' },
    { value: "el", content: 'Greek' },
    { value: "grc", content: 'Greek, Ancient(to 1453)' },
    { value: "kl", content: 'Greenlandic' },
    { value: "gn", content: 'Guarani' },
    { value: "gu", content: 'Gujarati' },
    { value: "gnn", content: 'Gumatj' },
    { value: "gup", content: 'Gunwinggu' },
    { value: "gbj", content: 'Gutob' },
    { value: "ht", content: 'Haitian' },
    { value: "hai", content: 'Haida' },
    { value: "hak", content: 'Hakka' },
    { value: "bgc", content: 'Haryanvi' },
    { value: "qav", content: 'Hassanya' },
    { value: "ha", content: 'Hausa' },
    { value: "haw", content: 'Hawaiian' },
    { value: "he", content: 'Hebrew' },
    { value: "hi", content: 'Hindi' },
    { value: "hmn", content: 'Hmong' },
    { value: "hoc", content: 'Ho' },
    { value: "qab", content: 'Hokkien' },
    { value: "hop", content: 'Hopi' },
    { value: "hu", content: 'Hungarian' },
    { value: "iba", content: 'Iban' },
    { value: "qag", content: 'Ibo' },
    { value: "is", content: 'Icelandic' },
    { value: "icl", content: 'Icelandic Sign Language' },
    { value: "ins", content: 'Indian Sign Language' },
    { value: "id", content: 'Indonesian' },
    { value: "iu", content: 'Inuktitut' },
    { value: "ik", content: 'Inupiaq' },
    { value: "ga", content: 'Irish Gaelic' },
    { value: "iru", content: 'Irula' },
    { value: "it", content: 'Italian' },
    { value: "ja", content: 'Japanese' },
    { value: "jsl", content: 'Japanese Sign Language' },
    { value: "dyo", content: 'Jola - Fonyi' },
    { value: "ktz", content: `Ju'hoan` },
    { value: "qbf", content: 'Kaado' },
    { value: "kea", content: 'Kabuverdianu' },
    { value: "kab", content: 'Kabyle' },
    { value: "xal", content: 'Kalmyk - Oirat' },
    { value: "kn", content: 'Kannada' },
    { value: "kpj", content: 'Karajá' },
    { value: "mjw", content: 'Karbi' },
    { value: "kar", content: 'Karen' },
    { value: "kk", content: 'Kazakh' },
    { value: "kca", content: 'Khanty' },
    { value: "kha", content: 'Khasi' },
    { value: "ki", content: 'Kikuyu' },
    { value: "rw", content: 'Kinyarwanda' },
    { value: "qar", content: 'Kirundi' },
    { value: "tlh", content: 'Klingon' },
    { value: "kfa", content: 'Kodava' },
    { value: "trp", content: 'Kokborok' },
    { value: "kok", content: 'Konkani' },
    { value: "ko", content: 'Korean' },
    { value: "kvk", content: 'Korean Sign Language' },
    { value: "khe", content: 'Korowai' },
    { value: "qaq", content: 'Kriolu' },
    { value: "kro", content: 'Kru' },
    { value: "kyw", content: 'Kudmali' },
    { value: "qbb", content: 'Kuna' },
    { value: "ku", content: 'Kurdish' },
    { value: "kgg", content: 'Kusunda' },
    { value: "kwk", content: 'Kwakiutl' },
    { value: "ky", content: 'Kyrgyz' },
    { value: "lbj", content: 'Ladakhi' },
    { value: "lad", content: 'Ladino' },
    { value: "lo", content: 'Lao' },
    { value: "la", content: 'Latin' },
    { value: "lv", content: 'Latvian' },
    { value: "lif", content: 'Limbu' },
    { value: "ln", content: 'Lingala' },
    { value: "lt", content: 'Lithuanian' },
    { value: "nds", content: 'Low German' },
    { value: "lb", content: 'Luxembourgish' },
    { value: "mk", content: 'Macedonian' },
    { value: "qbm", content: 'Macro - Jê' },
    { value: "mag", content: 'Magahi' },
    { value: "mai", content: 'Maithili' },
    { value: "mg", content: 'Malagasy' },
    { value: "ms", content: 'Malay' },
    { value: "ml", content: 'Malayalam' },
    { value: "pqm", content: 'Malecite - Passamaquoddy' },
    { value: "qap", content: 'Malinka' },
    { value: "mt", content: 'Maltese' },
    { value: "mnc", content: 'Manchu' },
    { value: "cmn", content: 'Mandarin' },
    { value: "man", content: 'Mandingo' },
    { value: "mni", content: 'Manipuri' },
    { value: "mi", content: 'Maori' },
    { value: "arn", content: 'Mapudungun' },
    { value: "mr", content: 'Marathi' },
    { value: "mh", content: 'Marshallese' },
    { value: "mas", content: 'Masai' },
    { value: "mls", content: 'Masalit' },
    { value: "myn", content: 'Maya' },
    { value: "men", content: 'Mende' },
    { value: "mic", content: 'Micmac' },
    { value: "enm", content: 'Middle English' },
    { value: "nan", content: 'Min Nan' },
    { value: "min", content: 'Minangkabau' },
    { value: "mwl", content: 'Mirandese' },
    { value: "qmt", content: 'Mixtec' },
    { value: "lus", content: 'Mizo' },
    { value: "moh", content: 'Mohawk' },
    { value: "mn", content: 'Mongolian' },
    { value: "moe", content: 'Montagnais' },
    { value: "qaf", content: 'More' },
    { value: "mfe", content: 'Morisyen' },
    { value: "qbl", content: 'Nagpuri' },
    { value: "nah", content: 'Nahuatl' },
    { value: "qba", content: 'Nama' },
    { value: "nv", content: 'Navajo' },
    { value: "nbf", content: 'Naxi' },
    { value: "nd", content: 'Ndebele' },
    { value: "nap", content: 'Neapolitan' },
    { value: "yrk", content: 'Nenets' },
    { value: "ne", content: 'Nepali' },
    { value: "ncg", content: `Nisga'a` },
    { value: "zxx", content: 'None' },
    { value: "non", content: 'Norse, Old' },
    { value: "nai", content: 'North American Indian' },
    { value: "no", content: 'Norwegian' },
    { value: "qbk", content: 'Nushi' },
    { value: "nyk", content: 'Nyaneka' },
    { value: "ny", content: 'Nyanja' },
    { value: "oc", content: 'Occitan' },
    { value: "oj", content: 'Ojibwa' },
    { value: "qaz", content: 'Ojihimba' },
    { value: "ang", content: 'Old English' },
    { value: "or", content: 'Oriya' },
    { value: "pap", content: 'Papiamento' },
    { value: "qaj", content: 'Parsee' },
    { value: "ps", content: 'Pashtu' },
    { value: "paw", content: 'Pawnee' },
    { value: "fa", content: 'Persian' },
    { value: "qai", content: 'Peul' },
    { value: "myp", content: 'Pirahã' },
    { value: "pl", content: 'Polish' },
    { value: "qah", content: 'Polynesian' },
    { value: "pt", content: 'Portuguese' },
    { value: "fuf", content: 'Pular' },
    { value: "pa", content: 'Punjabi' },
    { value: "tsz", content: 'Purepecha' },
    { value: "qu", content: 'Quechua' },
    { value: "qya", content: 'Quenya' },
    { value: "raj", content: 'Rajasthani' },
    { value: "qbj", content: 'Rawan' },
    { value: "xrr", content: 'Rhaetian' },
    { value: "ro", content: 'Romanian' },
    { value: "rm", content: 'Romansh' },
    { value: "rom", content: 'Romany' },
    { value: "rtm", content: 'Rotuman' },
    { value: "ru", content: 'Russian' },
    { value: "rsl", content: 'Russian Sign Language' },
    { value: "qao", content: 'Ryukyuan' },
    { value: "qae", content: 'Saami' },
    { value: "sm", content: 'Samoan' },
    { value: "sa", content: 'Sanskrit' },
    { value: "sat", content: 'Santali' },
    { value: "sc", content: 'Sardinian' },
    { value: "qay", content: 'Scanian' },
    { value: "sr", content: 'Serbian' },
    { value: "qbo", content: 'Serbo - Croatian' },
    { value: "srr", content: 'Serer' },
    { value: "qad", content: 'Shanghainese' },
    { value: "qau", content: 'Shanxi' },
    { value: "shp", content: 'Shipibo' },
    { value: "sn", content: 'Shona' },
    { value: "shh", content: 'Shoshoni' },
    { value: "scn", content: 'Sicilian' },
    { value: "qsg", content: 'Silbo Gomero' },
    { value: "sjn", content: 'Sindarin' },
    { value: "sd", content: 'Sindhi' },
    { value: "si", content: 'Sinhala' },
    { value: "sio", content: 'Sioux' },
    { value: "sk", content: 'Slovak' },
    { value: "sl", content: 'Slovenian' },
    { value: "so", content: 'Somali' },
    { value: "son", content: 'Songhay' },
    { value: "snk", content: 'Soninke' },
    { value: "wen", content: 'Sorbian languages' },
    { value: "st", content: 'Sotho' },
    { value: "qbe", content: 'Sousson' },
    { value: "es", content: 'Spanish' },
    { value: "ssp", content: 'Spanish Sign Language' },
    { value: "srn", content: 'Sranan' },
    { value: "sw", content: 'Swahili' },
    { value: "sv", content: 'Swedish' },
    { value: "gsw", content: 'Swiss German' },
    { value: "syl", content: 'Sylheti' },
    { value: "nmn", content: 'Taa' },
    { value: "tl", content: 'Tagalog' },
    { value: "tg", content: 'Tajik' },
    { value: "tmh", content: 'Tamashek' },
    { value: "ta", content: 'Tamil' },
    { value: "tac", content: 'Tarahumara' },
    { value: "tt", content: 'Tatar' },
    { value: "te", content: 'Telugu' },
    { value: "qak", content: 'Teochew' },
    { value: "th", content: 'Thai' },
    { value: "bo", content: 'Tibetan' },
    { value: "qan", content: 'Tigrigna' },
    { value: "tli", content: 'Tlingit' },
    { value: "tpi", content: 'Tok Pisin' },
    { value: "to", content: 'Tonga(Tonga Islands)' },
    { value: "ts", content: 'Tsonga' },
    { value: "tsc", content: 'Tswa' },
    { value: "tn", content: 'Tswana' },
    { value: "tcy", content: 'Tulu' },
    { value: "tup", content: 'Tupi' },
    { value: "tr", content: 'Turkish' },
    { value: "tk", content: 'Turkmen' },
    { value: "tyv", content: 'Tuvinian' },
    { value: "tue", content: 'Tuyuca' },
    { value: "tzo", content: 'Tzotzil' },
    { value: "uk", content: 'Ukrainian' },
    { value: "ukl", content: 'Ukrainian Sign Language' },
    { value: "qat", content: 'Ungwatsi' },
    { value: "ur", content: 'Urdu' },
    { value: "uz", content: 'Uzbek' },
    { value: "vi", content: 'Vietnamese' },
    { value: "qaa", content: 'Visayan' },
    { value: "was", content: 'Washoe' },
    { value: "cy", content: 'Welsh' },
    { value: "wo", content: 'Wolof' },
    { value: "xh", content: 'Xhosa' },
    { value: "sah", content: 'Yakut' },
    { value: "yap", content: 'Yapese' },
    { value: "yi", content: 'Yiddish' },
    { value: "yo", content: 'Yoruba' },
    { value: "ypk", content: 'Yupik' },
    { value: "zu", content: 'Zulu' },
]